title: TravelBudgetPro
description: "Your ultimate guide to budget travel tips, destination guides, and money-saving travel hacks for every adventurer."
url: "https://kkumakkuma.github.io"
baseurl: "/TravelBudgetPro"
permalink: /:year/:month/:day/:title/
future: true

theme: minima

author:
  name: TravelBudgetPro
  email: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

google_analytics: "G-HNHHZN7FHX"

exclude:
  - scripts/
  - .github/
  - README.md
  - Gemfile
  - Gemfile.lock
